# Generated by Django 2.2.1 on 2019-06-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('edad', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=20)),
            ],
        ),
    ]
