# Generated by Django 2.2.1 on 2019-06-17 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190616_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
