# Generated by Django 2.2.1 on 2019-06-24 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=450)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('Unidad', models.IntegerField()),
            ],
        ),
    ]
