# Generated by Django 2.2.1 on 2019-06-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190626_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='id_prod',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
    ]
